### ISSUE TITLE
当以数字作为键值时无法正确读取

### ISSUE THREAD

**Issue by XDawned** [Tryanks/python-snbtlib#5]
### 错误
在FTBQ的任务奖励中，支持玩家自定义奖励物品的一些tag
在这些tag中可能会出现以数字为键值的形式
会导致读取出现错误
`
industrialforegoing: {
									0: {
										Count: 1.0d
										id: "patchouli:guide_book"
										tag: {
											"patchouli:book": "industrialforegoing:industrial_foregoing"
										}
									}
								}
`
[snbt文件节选-出自ATM8](https://pastebin.ubuntu.com/p/cBPmq8FCcr/)

### 可能的解决思路
![image](https://github.com/Tryanks/python-snbtlib/assets/96915192/9eecb316-e173-4fa9-8beb-2d72d76219e0)

- 正常情况下某行肯定不会以数字打头，也就是非键值的数字前方肯定不会出现大范围的空格和换行，或许这可以作为鉴别这个数字是否为键值的一种方式

**Comment by Tryanks** [comment]
另一个可能的思路：重整结构，将“位于Key的位置”的一切内容视为Key。我白天会一下
