### ISSUE TITLE
错误的字符串数据归类

### ISSUE THREAD

**Issue by XDawned** [Tryanks/python-snbtlib#9]
![E} PQ)VPN9B%WQR7@IAOWFP](https://github.com/Tryanks/python-snbtlib/assets/96915192/f99357e4-6b47-4c3f-a111-0fa431c33956)

`B;`如果归为字符串会导致任务无法读取[任务原文](https://pastebin.ubuntu.com/p/qJnsXn7YRH/)

`B;`代表字节数组，`Sides: [B; 0b 0b 0b 0b 0b 0b]`表示一个字节长度为 6 的字节数组[资料来源](https://minecraft.fandom.com/zh/index.php?title=NBT%E6%A0%BC%E5%BC%8F&variant=zh-hans&redirect=no)
![image](https://github.com/Tryanks/python-snbtlib/assets/96915192/9f61544e-4ccf-4cee-ad7e-63a1c302b2f0)

除此之外dump时也会把true和false转化为字符串形式的“true”和“false”，但不影响读取

**Comment by Tryanks** [comment]
已经处理完成，但遇到问题：不知道如何处理为json
